services:
  - type: web
    name: mcp_tool_csp
    runtime: docker
    region: singapore
    plan: free
    repo: https://github.com/shekharapple16-spec/mcp_tool_csp
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
